"""Plan or execute one guarded reading-card note publication to Zotero.

Dry-run is the default. A real write requires ``--write --canary`` plus the exact
``--approved-plan`` generated by a prior live preflight. The command never writes
annotations, attachments, PDFs, collections, or top-level bibliographic fields.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sqlite3
import sys
import uuid
import urllib.request
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from typing import Any

RESEARCHOS_ROOT = Path(__file__).resolve().parents[3]
if str(RESEARCHOS_ROOT) not in sys.path:
    sys.path.insert(0, str(RESEARCHOS_ROOT))

from tools.reading_cards.card_common import (
    affiliation_publish_blockers,
    chinese_affiliation_display_blockers,
    content_sha256,
    parse_metadata,
    reading_card_identity,
    researchos_reading_card_notes,
)
from tools.reading_cards.reading_card_contract import validate_reading_card
from tools.researchos_outputs import (
    A003_READING_CARD_NOTE_PUBLISH,
    CORPUS_READING_CARDS_ROOT,
    CORPUS_ZOTERO_LIBRARY_DB,
    M005_READING_CARD_ANNOTATION_SYNC,
    ensure_output_dirs,
    write_json,
)
from tools.zotero.write.zotero_web_api import env_config, fetch_web_api_paged, selected_proxy
from tools.zotero.write.zotero_web_api import zotero_request as shared_zotero_request
from tools.zotero.zotero_library_index import (
    DEFAULT_LOCK_STALE_AFTER_SECONDS,
    acquire_writer_lock,
    init_db,
    release_writer_lock,
)


class ZoteroNotePublishError(RuntimeError):
    def __init__(self, status: int, message: str):
        super().__init__(f"HTTP {status}: {message}")
        self.status = status
        self.message = message


VOID_HTML_TAGS = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def safe_timestamp() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


class NoteContentParser(HTMLParser):
    """Preserve meaningful structure while ignoring known Zotero rewrites."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.tokens: list[tuple[Any, ...]] = []
        self.stack: list[tuple[str, bool]] = []

    def semantic_parent(self) -> str:
        for tag, ignored in reversed(self.stack):
            if not ignored:
                return tag
        return ""

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attrs_dict = dict(attrs)
        ignored = (
            (tag == "div" and attrs_dict.get("data-schema-version") is not None)
            or tag == "small"
            or (tag == "code" and self.semantic_parent() == "pre")
            or (tag == "p" and self.semantic_parent() == "blockquote")
        )
        normalized_attrs = tuple(
            sorted(
                (key, str(value or ""))
                for key, value in attrs
                if not (tag == "a" and key == "rel")
            )
        )
        if tag in VOID_HTML_TAGS:
            if not ignored:
                self.tokens.append(("void", tag, normalized_attrs))
            return
        self.stack.append((tag, ignored))
        if ignored:
            return
        self.tokens.append(("start", tag, normalized_attrs))

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)
        if tag not in VOID_HTML_TAGS:
            self.handle_endtag(tag)

    def handle_endtag(self, tag: str) -> None:
        ignored = False
        if self.stack:
            _opened_tag, ignored = self.stack.pop()
        if not ignored:
            self.tokens.append(("end", tag))

    def handle_data(self, data: str) -> None:
        normalized = re.sub(r"\s+", " ", data).strip()
        if normalized:
            self.tokens.append(("text", normalized))

    def normalized_tokens(self) -> list[tuple[Any, ...]]:
        """Drop only empty p/li nodes that Zotero interchanges during cleanup."""
        output: list[tuple[Any, ...]] = []
        index = 0
        while index < len(self.tokens):
            current = self.tokens[index]
            following = self.tokens[index + 1] if index + 1 < len(self.tokens) else None
            if (
                current[:2] in {("start", "p"), ("start", "li")}
                and following == ("end", current[1])
            ):
                index += 2
                continue
            output.append(current)
            index += 1
        return output


def note_content_hash(value: str) -> str:
    """Hash stable note structure after narrowly defined Zotero normalization."""
    parser = NoteContentParser()
    parser.feed(value)
    return sha256_text(json.dumps(parser.normalized_tokens(), ensure_ascii=False, separators=(",", ":")))


def strip_frontmatter(body: str) -> str:
    return re.sub(r"\A---\s*\n.*?\n---\s*\n", "", body, count=1, flags=re.S)


def strip_tags(value: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", "", value)).strip()


def render_inline(value: str) -> str:
    escaped = html.escape(strip_tags(value), quote=True)
    escaped = re.sub(
        r"\[([^\]]+)\]\(([^)]+)\)",
        # The source line is already escaped. Escaping the URL again would turn
        # ``&amp;`` into ``&amp;amp;`` and break page-plus-annotation links.
        lambda match: f'<a href="{match.group(2)}">{match.group(1)}</a>',
        escaped,
    )
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    return escaped


def markdown_to_zotero_html(body: str, card_id: str) -> str:
    """Render the stable reading-card subset without adding a new dependency."""
    source = strip_frontmatter(body)
    lines = source.splitlines()
    output = [f"<h1>ResearchOS 读书卡｜{html.escape(card_id)}</h1>"]
    paragraph: list[str] = []
    list_kind = ""
    in_code = False
    code_lines: list[str] = []

    def flush_paragraph() -> None:
        nonlocal paragraph
        if paragraph:
            output.append(f"<p>{render_inline(' '.join(paragraph))}</p>")
            paragraph = []

    def close_list() -> None:
        nonlocal list_kind
        if list_kind:
            output.append(f"</{list_kind}>")
            list_kind = ""

    for raw in lines:
        line = raw.rstrip()
        if line.strip().startswith("```"):
            flush_paragraph()
            close_list()
            if in_code:
                output.append("<pre><code>" + html.escape("\n".join(code_lines)) + "</code></pre>")
                code_lines = []
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        stripped = line.strip()
        if stripped in {"<details>", "</details>"} or stripped.startswith("<summary>"):
            continue
        if not stripped:
            flush_paragraph()
            close_list()
            continue
        heading = re.match(r"^(#{1,6})\s+(.+)$", stripped)
        if heading:
            flush_paragraph()
            close_list()
            level = min(len(heading.group(1)) + 1, 6)
            output.append(f"<h{level}>{render_inline(heading.group(2))}</h{level}>")
            continue
        if stripped.startswith(">"):
            flush_paragraph()
            close_list()
            output.append(f"<blockquote>{render_inline(stripped.lstrip('>').strip())}</blockquote>")
            continue
        unordered = re.match(r"^[-*]\s+(.+)$", stripped)
        ordered = re.match(r"^\d+[.)]\s+(.+)$", stripped)
        if unordered or ordered:
            flush_paragraph()
            wanted = "ul" if unordered else "ol"
            if list_kind != wanted:
                close_list()
                output.append(f"<{wanted}>")
                list_kind = wanted
            output.append(f"<li>{render_inline((unordered or ordered).group(1))}</li>")
            continue
        if re.fullmatch(r"[-*_]{3,}", stripped):
            flush_paragraph()
            close_list()
            output.append("<hr>")
            continue
        if stripped.startswith("|") and stripped.endswith("|"):
            flush_paragraph()
            close_list()
            output.append(f"<pre>{html.escape(stripped)}</pre>")
            continue
        paragraph.append(stripped)
    flush_paragraph()
    close_list()
    if in_code:
        output.append("<pre><code>" + html.escape("\n".join(code_lines)) + "</code></pre>")
    output.append(f"<p><small>ResearchOS card id: {html.escape(card_id)}</small></p>")
    return "\n".join(output)


def note_marker(card_id: str) -> str:
    return f"ResearchOS 读书卡｜{card_id}"


def request(
    config: dict[str, str],
    method: str,
    path: str,
    body: Any | None = None,
    headers: dict[str, str] | None = None,
    opener: urllib.request.OpenerDirector | None = None,
) -> tuple[int, dict[str, str], Any]:
    return shared_zotero_request(
        config,
        method,
        path,
        body,
        headers,
        opener,
        error_cls=ZoteroNotePublishError,
    )


def fetch_paged(config: dict[str, str], endpoint: str, opener: urllib.request.OpenerDirector) -> list[dict[str, Any]]:
    def request_fn(cfg: dict[str, str], method: str, path: str, body: Any | None, headers: dict[str, str] | None):
        return request(cfg, method, path, body, headers, opener)

    return fetch_web_api_paged(config, endpoint, request_fn, ZoteroNotePublishError)


def existing_generated_notes(children: list[dict[str, Any]], card_id: str) -> list[dict[str, Any]]:
    marker = note_marker(card_id)
    return [
        row
        for row in children
        if (row.get("data", {}) or {}).get("itemType") == "note"
        and marker in str((row.get("data", {}) or {}).get("note") or "")
    ]


def safe_children_snapshot(children: list[dict[str, Any]], card_id: str) -> list[dict[str, Any]]:
    """Keep audit identity without persisting unrelated human note bodies."""
    marker = note_marker(card_id)
    snapshot: list[dict[str, Any]] = []
    for row in children:
        data = row.get("data", {}) or {}
        item_type = str(data.get("itemType") or "")
        entry: dict[str, Any] = {
            "key": row.get("key") or data.get("key"),
            "version": row.get("version") or data.get("version"),
            "itemType": item_type,
            "parentItem": data.get("parentItem"),
        }
        if item_type == "attachment":
            entry.update({
                "title": data.get("title"),
                "contentType": data.get("contentType"),
                "linkMode": data.get("linkMode"),
            })
        elif item_type == "note":
            note_html = str(data.get("note") or "")
            entry.update({
                "note_hash": sha256_text(note_html),
                "is_target_generated_note": marker in note_html,
            })
        snapshot.append(entry)
    return snapshot


def mapped_note_state(db_path: Path, card_id: str) -> dict[str, Any] | None:
    if not db_path.exists():
        return None
    with sqlite3.connect(db_path) as conn:
        table = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'reading_card_zotero_notes'"
        ).fetchone()
        if not table:
            return None
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM reading_card_zotero_notes WHERE card_id = ?",
            (card_id,),
        ).fetchone()
        return dict(row) if row else None


def build_plan(
    card_path: Path,
    root: Path,
    db_path: Path,
    config: dict[str, str],
    opener: urllib.request.OpenerDirector,
    proxy_info: dict[str, str],
) -> tuple[dict[str, Any], str, dict[str, Any], list[dict[str, Any]]]:
    body = card_path.read_text(encoding="utf-8-sig")
    card_id, item_key = reading_card_identity(body, card_path)
    if not card_id or not item_key:
        raise SystemExit("Reading card must provide card_id and Zotero item key")
    contract = validate_reading_card(body, expected_item_key=item_key)
    note_html = markdown_to_zotero_html(body, card_id)
    status, _headers, parent_item = request(config, "GET", f"items/{item_key}", opener=opener)
    if status != 200 or (parent_item.get("data", {}) or {}).get("itemType") in {"note", "attachment", "annotation"}:
        raise SystemExit("Target item is missing or is not a top-level bibliographic item")
    children = fetch_paged(config, f"items/{item_key}/children", opener)
    matches = existing_generated_notes(children, card_id)
    parent_generated_notes = researchos_reading_card_notes(children)
    mapping = mapped_note_state(db_path, card_id)
    metadata = parse_metadata(body)
    blockers = affiliation_publish_blockers(metadata)
    blockers.extend(chinese_affiliation_display_blockers(metadata))
    blockers.extend(f"reading_card_contract:{code}" for code in contract.issue_codes)
    action = "create"
    existing_note: dict[str, Any] | None = None
    if len(parent_generated_notes) > 1:
        blockers.append("multiple_parent_reading_card_notes")
        action = "blocked"
    elif len(parent_generated_notes) == 1 and not matches:
        blockers.append("parent_reading_card_note_identity_conflict")
        action = "blocked"
    elif len(matches) == 1:
        existing_note = matches[0]
        existing_html = str((existing_note.get("data", {}) or {}).get("note") or "")
        existing_content_hash = note_content_hash(existing_html)
        existing_tags = {
            str(row.get("tag") or "")
            for row in ((existing_note.get("data", {}) or {}).get("tags") or [])
            if isinstance(row, dict)
        }
        if "rs:reading-card" not in existing_tags:
            blockers.append("generated_note_missing_tag")
            action = "blocked"
        elif existing_content_hash == note_content_hash(note_html):
            action = "noop"
        elif not mapping or mapping.get("note_key") != existing_note.get("key"):
            blockers.append("existing_note_not_tracked")
            action = "blocked"
        elif mapping.get("published_note_hash") not in {existing_content_hash, sha256_text(existing_html)}:
            blockers.append("existing_note_changed_outside_researchos")
            action = "blocked"
        else:
            action = "update"
    if blockers:
        action = "blocked"
    relative_card = str(card_path.relative_to(root)).replace("\\", "/") if card_path.is_relative_to(root) else card_path.name
    plan = {
        "schema_version": 2,
        "generated_at": utc_now(),
        "mode": "zotero_reading_card_note_canary",
        "card_id": card_id,
        "card_path": relative_card,
        "item_key": item_key,
        "action": action,
        "source_hash": content_sha256(body),
        "note_html_hash": sha256_text(note_html),
        "note_content_hash": note_content_hash(note_html),
        "reading_card_contract": contract.to_dict(),
        "existing_note_key": existing_note.get("key") if existing_note else "",
        "existing_note_version": existing_note.get("version") if existing_note else None,
        "existing_note_hash": sha256_text(str((existing_note.get("data", {}) or {}).get("note") or "")) if existing_note else "",
        "existing_note_content_hash": note_content_hash(str((existing_note.get("data", {}) or {}).get("note") or "")) if existing_note else "",
        "mapping_repair_needed": bool(
            action == "noop"
            and mapping
            and mapping.get("note_key") == (existing_note or {}).get("key")
            and mapping.get("published_note_hash")
            != note_content_hash(str(((existing_note or {}).get("data", {}) or {}).get("note") or ""))
        ),
        "blocking_conditions": blockers,
        "policy": {
            "one_parent_item": True,
            "one_generated_note": True,
            "never_write_annotations": True,
            "never_delete_automatically": True,
            "require_version_match": True,
            "require_explicit_approved_plan": True,
        },
        "proxy": proxy_info,
    }
    return plan, note_html, parent_item, children


def repair_noop_mapping(db_path: Path, plan: dict[str, Any], note: dict[str, Any], card_path: str) -> None:
    """Repair only a tracked local mapping after semantic equality is verified."""
    mapping = mapped_note_state(db_path, plan["card_id"])
    if not mapping or mapping.get("note_key") != note.get("key"):
        raise SystemExit("Local mapping repair requires an existing matching note mapping")
    if plan.get("action") != "noop" or plan.get("existing_note_content_hash") != plan.get("note_content_hash"):
        raise SystemExit("Local mapping repair requires a semantically identical Zotero note")
    note_html = str((note.get("data", {}) or {}).get("note") or "")
    with sqlite3.connect(db_path) as conn:
        conn.execute(
            """
            UPDATE reading_card_zotero_notes
            SET card_path = ?, note_version = ?, source_hash = ?,
                published_note_hash = ?, publish_status = 'published', last_planned_at = ?
            WHERE card_id = ? AND note_key = ?
            """,
            (
                card_path,
                note.get("version"),
                plan["source_hash"],
                note_content_hash(note_html),
                plan["generated_at"],
                plan["card_id"],
                note.get("key"),
            ),
        )
        conn.commit()


def plan_command(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve() if args.root else RESEARCHOS_ROOT
    ensure_output_dirs(root)
    card_path = Path(args.card)
    if not card_path.is_absolute():
        card_path = root / card_path
    db_path = Path(args.db)
    if not db_path.is_absolute():
        db_path = root / db_path
    config = env_config()
    opener, proxy_info = selected_proxy()
    plan, note_html, parent_item, children = build_plan(card_path, root, db_path, config, opener, proxy_info)
    output_dir = root / M005_READING_CARD_ANNOTATION_SYNC / f"{safe_timestamp()}-note-preflight"
    output_dir.mkdir(parents=True, exist_ok=True)
    plan["plan_dir"] = str(output_dir.relative_to(root)).replace("\\", "/")
    write_json(output_dir / "approved-plan-candidate.json", plan)
    (output_dir / "note-preview.html").write_text(note_html + "\n", encoding="utf-8")
    write_json(output_dir / "parent-item-before.json", parent_item)
    write_json(output_dir / "children-before.json", safe_children_snapshot(children, plan["card_id"]))
    local_mapping_repaired = False
    if args.repair_local_mapping:
        if plan["action"] != "noop" or len(existing_generated_notes(children, plan["card_id"])) != 1:
            raise SystemExit("--repair-local-mapping requires exactly one semantically identical generated note")
        lock_path = acquire_writer_lock(db_path, args.lock_stale_after, args.force_lock)
        try:
            repair_noop_mapping(
                db_path,
                plan,
                existing_generated_notes(children, plan["card_id"])[0],
                plan["card_path"],
            )
            local_mapping_repaired = True
        finally:
            release_writer_lock(lock_path)
    print(json.dumps({
        "action": plan["action"],
        "card_id": plan["card_id"],
        "item_key": plan["item_key"],
        "blocking_conditions": plan["blocking_conditions"],
        "mapping_repair_needed": plan["mapping_repair_needed"],
        "local_mapping_repaired": local_mapping_repaired,
        "plan": str((output_dir / "approved-plan-candidate.json").relative_to(root)).replace("\\", "/"),
        "preview": str((output_dir / "note-preview.html").relative_to(root)).replace("\\", "/"),
    }, ensure_ascii=False, indent=2))
    return 0 if not plan["blocking_conditions"] else 2


def validate_approved_plan(plan: dict[str, Any]) -> dict[str, Any]:
    if plan.get("schema_version") != 2 or plan.get("mode") != "zotero_reading_card_note_canary":
        raise SystemExit("Approved plan has an unsupported schema or mode")
    policy = plan.get("policy", {})
    required = (
        "one_parent_item",
        "one_generated_note",
        "never_write_annotations",
        "never_delete_automatically",
        "require_version_match",
        "require_explicit_approved_plan",
    )
    if any(policy.get(key) is not True for key in required):
        raise SystemExit("Approved plan is missing mandatory safety policy flags")
    if plan.get("blocking_conditions") != [] or plan.get("action") not in {"create", "update"}:
        raise SystemExit("Approved plan is blocked or has no write action")
    if not re.fullmatch(r"[A-Za-z0-9._-]+", str(plan.get("card_id") or "")):
        raise SystemExit("Approved plan has an invalid card_id")
    if not re.fullmatch(r"[A-Z0-9]{8}", str(plan.get("item_key") or "")):
        raise SystemExit("Approved plan has an invalid Zotero item key")
    for field in ("source_hash", "note_html_hash", "note_content_hash"):
        if not re.fullmatch(r"[0-9a-f]{64}", str(plan.get(field) or "")):
            raise SystemExit(f"Approved plan has an invalid {field}")
    contract = plan.get("reading_card_contract")
    if not isinstance(contract, dict) or contract.get("valid") is not True:
        raise SystemExit("Approved plan is missing a valid reading-card contract receipt")
    if not re.fullmatch(r"[0-9a-f]{64}", str(contract.get("receipt_hash") or "")):
        raise SystemExit("Approved plan has an invalid reading-card contract receipt hash")
    raw_card_path = str(plan.get("card_path") or "").strip()
    card_path = Path(raw_card_path)
    if not raw_card_path or card_path.is_absolute() or ".." in card_path.parts:
        raise SystemExit("Approved plan card_path must be a safe relative path")
    if not str(plan.get("generated_at") or "") or not str(plan.get("plan_dir") or ""):
        raise SystemExit("Approved plan is missing generation provenance")
    if plan["action"] == "create":
        if plan.get("existing_note_key") or plan.get("existing_note_version") is not None or plan.get("existing_note_hash"):
            raise SystemExit("Create plan unexpectedly contains an existing note state")
    else:
        if not re.fullmatch(r"[A-Z0-9]{8}", str(plan.get("existing_note_key") or "")):
            raise SystemExit("Update plan has an invalid existing note key")
        if not isinstance(plan.get("existing_note_version"), int) or int(plan["existing_note_version"]) < 0:
            raise SystemExit("Update plan has an invalid existing note version")
        if not re.fullmatch(r"[0-9a-f]{64}", str(plan.get("existing_note_hash") or "")):
            raise SystemExit("Update plan has an invalid existing note hash")
    return plan


def read_approved_plan(path: Path) -> dict[str, Any]:
    return validate_approved_plan(json.loads(path.read_text(encoding="utf-8-sig")))


def require_path_within(path: Path, parent: Path, label: str) -> Path:
    resolved = path.resolve()
    allowed = parent.resolve()
    if not resolved.is_relative_to(allowed):
        raise SystemExit(f"{label} must stay within {allowed}")
    return resolved


def note_postcondition_errors(
    plan: dict[str, Any],
    note_key: str,
    note_after: dict[str, Any],
    expected_html: str,
) -> list[str]:
    data = note_after.get("data", {}) or {}
    actual_key = str(note_after.get("key") or data.get("key") or "")
    tags = {
        str(row.get("tag") or "")
        for row in (data.get("tags") or [])
        if isinstance(row, dict)
    }
    errors: list[str] = []
    if actual_key != note_key:
        errors.append("note_key_mismatch")
    if data.get("itemType") != "note":
        errors.append("item_type_mismatch")
    if str(data.get("parentItem") or "") != plan["item_key"]:
        errors.append("parent_item_mismatch")
    if "rs:reading-card" not in tags:
        errors.append("reading_card_tag_missing")
    actual_html = str(data.get("note") or "")
    if note_content_hash(actual_html) != note_content_hash(expected_html):
        errors.append("note_content_mismatch")
    version = note_after.get("version") or data.get("version")
    if not isinstance(version, int):
        errors.append("note_version_missing")
    elif plan["action"] == "update" and version <= int(plan["existing_note_version"]):
        errors.append("note_version_not_advanced")
    return errors


def save_mapping(db_path: Path, plan: dict[str, Any], note: dict[str, Any], card_path: str) -> None:
    data = note.get("data", {}) or {}
    note_html = str(data.get("note") or "")
    with sqlite3.connect(db_path) as conn:
        init_db(conn)
        conn.execute(
            """
            INSERT INTO reading_card_zotero_notes (
              card_id, item_key, card_path, note_key, note_version, source_hash,
              published_note_hash, publish_status, last_planned_at, last_published_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, 'published', ?, ?)
            ON CONFLICT(card_id) DO UPDATE SET
              item_key=excluded.item_key,
              card_path=excluded.card_path,
              note_key=excluded.note_key,
              note_version=excluded.note_version,
              source_hash=excluded.source_hash,
              published_note_hash=excluded.published_note_hash,
              publish_status='published',
              last_planned_at=excluded.last_planned_at,
              last_published_at=excluded.last_published_at
            """,
            (
                plan["card_id"],
                plan["item_key"],
                card_path,
                note.get("key"),
                note.get("version"),
                plan["source_hash"],
                note_content_hash(note_html),
                plan["generated_at"],
                utc_now(),
            ),
        )
        conn.commit()


def write_command(args: argparse.Namespace) -> int:
    if not args.canary:
        raise SystemExit("Real note publication requires --canary")
    if not args.approved_plan:
        raise SystemExit("Real note publication requires --approved-plan")
    root = Path(args.root).resolve() if args.root else RESEARCHOS_ROOT
    ensure_output_dirs(root)
    plan_path = Path(args.approved_plan)
    if not plan_path.is_absolute():
        plan_path = root / plan_path
    plan_path = require_path_within(plan_path, root / M005_READING_CARD_ANNOTATION_SYNC, "Approved plan")
    if plan_path.name != "approved-plan-candidate.json":
        raise SystemExit("Approved plan must be the generated approved-plan-candidate.json")
    plan = read_approved_plan(plan_path)
    expected_plan_dir = str(plan_path.parent.relative_to(root)).replace("\\", "/")
    if plan["plan_dir"] != expected_plan_dir:
        raise SystemExit("Approved plan provenance does not match its directory")
    card_path = require_path_within(
        root / plan["card_path"],
        root / CORPUS_READING_CARDS_ROOT / "cards",
        "Reading card",
    )
    card_body = card_path.read_text(encoding="utf-8-sig")
    evidence_blockers = affiliation_publish_blockers(parse_metadata(card_body))
    if evidence_blockers:
        raise SystemExit("Reading card affiliation evidence is not publishable: " + ", ".join(evidence_blockers))
    contract = validate_reading_card(card_body, expected_item_key=plan["item_key"])
    if not contract.valid:
        raise SystemExit("Reading card contract is not publishable: " + ", ".join(contract.issue_codes))
    if contract.to_dict()["receipt_hash"] != plan["reading_card_contract"]["receipt_hash"]:
        raise SystemExit("Reading card contract changed after dry-run; generate a new plan")
    note_html = markdown_to_zotero_html(card_body, plan["card_id"])
    if content_sha256(card_body) != plan["source_hash"] or sha256_text(note_html) != plan["note_html_hash"]:
        raise SystemExit("Reading card changed after dry-run; generate a new plan")
    db_path = Path(args.db)
    if not db_path.is_absolute():
        db_path = root / db_path

    config = env_config()
    opener, proxy_info = selected_proxy()
    run_dir = root / A003_READING_CARD_NOTE_PUBLISH / f"{safe_timestamp()}-canary"
    run_dir.mkdir(parents=True, exist_ok=True)
    write_json(run_dir / "proxy-info.redacted.json", proxy_info)
    write_json(run_dir / "approved-plan.json", plan)
    lock_path = acquire_writer_lock(db_path, args.lock_stale_after, args.force_lock)
    try:
        parent_status, _headers, parent_before = request(config, "GET", f"items/{plan['item_key']}", opener=opener)
        parent_data = parent_before.get("data", {}) or {}
        parent_key = str(parent_before.get("key") or parent_data.get("key") or "")
        if (
            parent_status != 200
            or parent_key != plan["item_key"]
            or parent_data.get("itemType") in {"note", "attachment", "annotation"}
        ):
            raise SystemExit("Live state changed: target is not the planned top-level bibliographic item")
        children_before = fetch_paged(config, f"items/{plan['item_key']}/children", opener)
        matches = existing_generated_notes(children_before, plan["card_id"])
        if plan["action"] == "create" and matches:
            raise SystemExit("Live state changed: generated note now exists")
        if plan["action"] == "update":
            if len(matches) != 1 or matches[0].get("key") != plan["existing_note_key"]:
                raise SystemExit("Live state changed: planned note no longer matches")
            current = matches[0]
            if current.get("version") != plan["existing_note_version"] or sha256_text(str((current.get("data", {}) or {}).get("note") or "")) != plan["existing_note_hash"]:
                raise SystemExit("Live state changed: note version or content no longer matches")
        write_json(run_dir / "parent-item-before.json", parent_before)
        write_json(run_dir / "children-before.json", safe_children_snapshot(children_before, plan["card_id"]))

        if plan["action"] == "create":
            payload = [{
                "itemType": "note",
                "parentItem": plan["item_key"],
                "note": note_html,
                "tags": [{"tag": "rs:reading-card"}],
            }]
            status, _response_headers, response = request(
                config,
                "POST",
                "items",
                payload,
                {"Zotero-Write-Token": uuid.uuid4().hex},
                opener,
            )
            if status != 200 or not (response or {}).get("success", {}).get("0"):
                raise ZoteroNotePublishError(status, "Zotero did not return a created note key")
            note_key = str(response["success"]["0"])
            before_note: dict[str, Any] | None = None
        else:
            note_key = str(plan["existing_note_key"])
            before_note = matches[0]
            status, _response_headers, _response = request(
                config,
                "PATCH",
                f"items/{note_key}",
                {"note": note_html},
                {"If-Unmodified-Since-Version": str(plan["existing_note_version"])},
                opener,
            )
            if status != 204:
                raise ZoteroNotePublishError(status, "Unexpected note update status")
        note_after_error = ""
        try:
            note_after_status, _headers, note_after = request(config, "GET", f"items/{note_key}", opener=opener)
        except Exception as exc:
            note_after_status = 0
            note_after = {}
            note_after_error = type(exc).__name__
        write_json(run_dir / "note-before.json", before_note)
        write_json(run_dir / "note-after.json", note_after)
        if note_after_error:
            write_json(run_dir / "note-after-error.json", {"error_type": note_after_error})
        if plan["action"] == "create":
            rollback = {
                "requires_separate_delete_approval": True,
                "method": "DELETE",
                "endpoint": f"items/{note_key}",
                "if_unmodified_since_version": note_after.get("version"),
                "automatic_execution": False,
            }
        else:
            rollback = {
                "requires_separate_restore_approval": True,
                "method": "PATCH",
                "endpoint": f"items/{note_key}",
                "if_unmodified_since_version": note_after.get("version"),
                "restore_note": str((before_note.get("data", {}) or {}).get("note") or "") if before_note else "",
                "automatic_execution": False,
            }
        write_json(run_dir / "rollback-plan.json", rollback)
        postcondition_errors = note_postcondition_errors(plan, note_key, note_after, note_html)
        if note_after_error:
            postcondition_errors.insert(0, f"note_after_fetch_failed_{note_after_error}")
        elif note_after_status != 200:
            postcondition_errors.insert(0, f"unexpected_note_get_status_{note_after_status}")
        write_json(
            run_dir / "postcondition.json",
            {
                "verified": not postcondition_errors,
                "errors": postcondition_errors,
                "expected_note_content_hash": note_content_hash(note_html),
                "actual_note_content_hash": note_content_hash(str((note_after.get("data", {}) or {}).get("note") or "")),
            },
        )
        if postcondition_errors:
            failure_summary = {
                "generated_at": utc_now(),
                "mode": "canary_write",
                "action": plan["action"],
                "card_id": plan["card_id"],
                "item_key": plan["item_key"],
                "note_key": note_key,
                "note_version": note_after.get("version"),
                "write_performed": True,
                "postcondition_verified": False,
                "errors": postcondition_errors,
                "run_dir": str(run_dir.relative_to(root)).replace("\\", "/"),
            }
            write_json(run_dir / "summary.json", failure_summary)
            print(json.dumps(failure_summary, ensure_ascii=False, indent=2))
            return 3
        save_mapping(db_path, plan, note_after, plan["card_path"])
        summary = {
            "generated_at": utc_now(),
            "mode": "canary_write",
            "action": plan["action"],
            "card_id": plan["card_id"],
            "item_key": plan["item_key"],
            "note_key": note_key,
            "note_version": note_after.get("version"),
            "write_performed": True,
            "postcondition_verified": True,
            "run_dir": str(run_dir.relative_to(root)).replace("\\", "/"),
        }
        write_json(run_dir / "summary.json", summary)
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return 0
    finally:
        release_writer_lock(lock_path)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root")
    parser.add_argument("--db", default=str(CORPUS_ZOTERO_LIBRARY_DB))
    parser.add_argument("--card", help="Reading card path for dry-run preflight.")
    parser.add_argument("--approved-plan", help="Exact approved plan path for a canary write.")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--canary", action="store_true")
    parser.add_argument(
        "--repair-local-mapping",
        action="store_true",
        help="Repair only a tracked local mapping when the live note is semantically identical.",
    )
    parser.add_argument("--lock-stale-after", type=int, default=DEFAULT_LOCK_STALE_AFTER_SECONDS)
    parser.add_argument("--force-lock", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.lock_stale_after < 0:
        raise SystemExit("--lock-stale-after must be >= 0")
    if args.write:
        if args.repair_local_mapping:
            raise SystemExit("--repair-local-mapping cannot be combined with --write")
        return write_command(args)
    if not args.card:
        raise SystemExit("Dry-run preflight requires --card")
    return plan_command(args)


if __name__ == "__main__":
    raise SystemExit(main())
